spring:
  application:
    name: booking-room-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  # hidernate:
  #   ddl-auto: auto
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://db.evnmidplpysgsgfmxteg.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: BlueLabel@77.
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
