# Server properties
server:
  servlet:
    context-path: /
  port: 8081
#  address: 192.168.2.57

# Spring properties
spring:
  # h2 is active by default. This value can be overwritten by java arg param
  profiles:
    active: h2
  application:
    name: grades-api
  messages:
    basename: messages/Messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
