INSERT INTO client (NAME,EMAIL) VALUES ('David','david@bf.co');
INSERT INTO CLIENT (NAME,EMAIL) VALUES ('David2','david2@bf.co');
INSERT INTO CLIENT (NAME,EMAIL) VALUES ('Luis','luis@bf.co');
INSERT INTO ROOM (NAME,LOCATION,CAPACITY, START_TIME,FINISH_TIME,IS_ACTIVE) VALUES ('Room 1', 'Medellín',3,7,17,TRUE);
INSERT INTO ROOM (NAME,LOCATION,CAPACITY, START_TIME,FINISH_TIME,IS_ACTIVE) VALUES ('Room 2', 'Bogotá',3,6,13,TRUE);
INSERT INTO ROOM (NAME,LOCATION,CAPACITY, START_TIME,FINISH_TIME,IS_ACTIVE) VALUES ('Room 3', 'Marinilla',3,9,20,TRUE);
INSERT INTO BOOKING (DATE,END_TIME, START_TIME, ROOM_ID, USER_ID) VALUES ('2023-07-31',12,8,1,1);
INSERT INTO BOOKING (DATE,END_TIME, START_TIME, ROOM_ID, USER_ID) VALUES ('2023-07-28',14,9,2,2);